services:
  db:
    image: mongo
    env_file:
      - ./backend/.env
      - ./backend/.env.docker
    volumes:
      - ./backend/.dataBase/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo_test_data:/data/db

  app:
    build: ./backend
    env_file:
      - ./backend/.env
      - ./backend/.env.docker
    depends_on:
      - db
    command: npm run test:docker

volumes:
  mongo_test_data:
